mise_global_python_packages:
  - pip
  - pre-commit
  - ansible
  - ansible-lint
mise_global_node_packages:
  - npm
  - yarn
  - pnpm
mise_global_go_packages:
  - github.com/air-verse/air@latest
  - github.com/sqlc-dev/sqlc/cmd/sqlc@latest
  - github.com/golang-migrate/migrate/v4/cmd/migrate@latest
mise_global_rust_crates:
  - oha
mise_plugins:
  - name: supabase-cli
    repo: https://github.com/gavinying/asdf-supabase-cli
