apiVersion: v1
kind: Service
metadata:
  name: {{ include "solidtime.fullname" . }}
  labels:
    {{- include "solidtime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "solidtime.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
  labels:
    {{- include "solidtime-gotenberg.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gotenberg.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "solidtime-gotenberg.selectorLabels" . | nindent 4 }}
