base_system_packages:
  - alsa-utils
  - apache2-utils
  - apt-transport-https
  - asciinema
  - automake
  - autotools-dev
  - bat
  - bind9-dnsutils
  - bison
  - btop
  - build-essential
  - ca-certificates
  - clang
  - clang-17
  - cmake
  - cowsay
  - curl
  - direnv
  - dvipng
  - flex
  - fzf
  - gcc
  - gcc-11
  - gcc-12
  - gedit
  - git
  - gnome-keyring
  - gnupg
  - gnupg2
  - gpg
  - g++
  - hping3
  - htop
  - icu-devtools
  - iperf3
  - libayatana-appindicator3-dev
  - libbz2-dev
  - libcurl4-openssl-dev
  - libc6
  - libc6-dev
  - libffi-dev
  - libfuse2
  - libgl1
  - libglib2.0-0
  - libgtk-3-dev
  - libicu-dev
  - liblzma-dev
  - libncursesw5-dev
  - libnotify-dev
  - libnss3
  - libnss3-tools
  - libreadline-dev
  - librsvg2-dev
  - libsqlite3-dev
  - libssl-dev
  - libwebkit2gtk-4.1-dev
  - libxdo-dev
  - libxmlsec1-dev
  - libxml2-dev
  - libxss1
  - libyaml-dev
  - llvm-17
  - lolcat
  - lsb-release
  - mesa-utils
  - nasm
  - neofetch
  - ncat
  - net-tools
  - pass
  - portaudio19-dev
  - pv
  - python3
  - ripgrep
  - sshpass
  - tesseract-ocr
  - tk-dev
  - traceroute
  - tmux
  - unzip
  - upx-ucl
  - uuid-dev
  - uuid-runtime
  - wget
  - xsel
  - xz-utils
  - x11-apps
  - yacc
  - zlib1g-dev
  - zsh
  - zsh-syntax-highlighting
base_brew_packages:
  - git-xet
