apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{- include "tandoor.fullname" . }}-configmap'
  labels:
    {{- include "tandoor.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  DB_ENGINE: "django.db.backends.postgresql"
  POSTGRES_HOST: "10.10.10.103"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "tandoor"
  POSTGRES_DB: "tandoor"
